### ISSUE TITLE
Missing backend setting in torch UI

### ISSUE THREAD

**Issue by Neshura87** [StalkR/Space-Engineers-Link-Steam-Discord#5]
Torch Plugins Tab does not display any config options for the Plugin on the Frontend

![image](https://github.com/StalkR/Space-Engineers-Link-Steam-Discord/assets/48772737/33261f23-1aa9-4634-8941-ed645e11bf6d)

I used the in-built Plugin browser to install it, did I miss a step for the installation perhaps?

**Comment by StalkR** [comment]
Weird, it should show, thanks for the report I'll take a look today.

**Comment by StalkR** [comment]
I can reproduce, it also doesn't show the settings, the uploaded plugin seems broken: it should be v1.0.1 (it is on torchapi website) but inside the zip it's v1.0.0 somehow. I'll try to release a new version see if it fixes.

**Comment by StalkR** [comment]
Yes that fixed it, please restart torch, the plugin will auto-update and version v1.0.2 should show the settings:
![image](https://github.com/StalkR/Space-Engineers-Link-Steam-Discord/assets/1389952/3ee882ff-e253-4e24-9c24-197889306e9a)

Thanks again for the bug report!
